name = "portfolio-arull"
compatibility_date = "2024-01-01"
pages_build_output_dir = "build"

[[pages_build_config]]
# Build command and output directory
build_command = "npm run build"
destination_dir = "build"